/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;
import static java.lang.Thread.sleep;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Anirudh
 */
public class AdminLogin extends DesignHome 
{
ResultSet rs1;
    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
        
        clock();
    }

    public void logout()
    {
        try
        {
        String uid = "";
            con = new DesignHome().dbconn();
            String que = "Select userid, sno from ActivityLog order by Sno desc limit 1";
            stmt = con.createStatement();
            rs = stmt.executeQuery(que);
            int sno = 0;
            while(rs.next())
            {
                uid = rs.getString(1);
                sno = rs.getInt(2);
            }

            System.out.println("UserID = " + uid);
            
            String query = "update ActivityLog set logout = ? where sno = '" + sno + "';";
            pstmt = con.prepareStatement(query);

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            java.util.Date date = new java.util.Date();
            sdf.format(date);
            String datetime = date.toString();

            pstmt.setString(1, datetime);
            pstmt.executeUpdate();
            
            stmt.close();
            pstmt.close();
            rs.close();
            con.close();
            
            new Home().setVisible(true);
            this.dispose();
        }
    
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    public void clock()
    {
        Thread clock = new Thread()
        {
            public void run()
            {
                try 
                {
                    for(;;)
                    {
                        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                        java.util.Date date = new java.util.Date();
                        ClockLbl.setText(sdf.format(date)); 
                        sleep(1000);
                    }
                }
                catch (InterruptedException ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }        
        };
        clock.start();
    }
    
    
    public void logincheck()
    {
        String uname = UserNameTxt.getText();
        String password = new String(PassTxt.getPassword());
        String encpass = getMD5(password);
        String dbpass = "";
        String Isadmin="";
        
        if(uname.equals("") || password.equals(""))
            JOptionPane.showMessageDialog(null, "None Of The Fields Can Be Empty");
        
        else
        {
            try
            {
                con = new DesignHome().dbconn();
                con.setAutoCommit(false);

                String query = "Select password from users where username = '" + uname + "'";
                stmt = con.createStatement();
                rs = stmt.executeQuery(query);
                
                stmt1 = con.createStatement();
                String query1 = "select isadmin from users where username = '" + uname + "'";
                rs1 = stmt1.executeQuery(query1);
                if(rs.next())
                    {
                        dbpass = rs.getString("password");
                        if(rs1.next())
                        {
                            Isadmin = rs1.getString(1);
                        }
                    }
                if(dbpass.equals(encpass))
                    {
                        if(Isadmin.equals("True"))
                        {
                        new AdminMainMenu().setVisible(true);
                        this.dispose();
                        }
                        else
                        JOptionPane.showMessageDialog(null, "User does not have admin rights");
                    }
                else
                JOptionPane.showMessageDialog(null, "Invalid credentials");
            }
            
            catch(SQLException E)
            {
                JOptionPane.showMessageDialog(null, E.getMessage());
            }
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PassLbl = new javax.swing.JLabel();
        UsernameLbl = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        UserNameTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        PassTxt = new javax.swing.JPasswordField();
        LoginBtn = new javax.swing.JButton();
        ChangePassBtn = new javax.swing.JButton();
        RelSettingLbl = new javax.swing.JLabel();
        ClockLbl = new javax.swing.JLabel();
        HeadingLbl = new javax.swing.JLabel();
        LogOutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PassLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PassLbl.setForeground(new java.awt.Color(255, 255, 255));
        PassLbl.setText("Enter your Password :");
        jPanel1.add(PassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        UsernameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UsernameLbl.setForeground(new java.awt.Color(255, 255, 255));
        UsernameLbl.setText("Enter your UserName :");
        jPanel1.add(UsernameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/show_password_32px.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 30, 30));

        BackBtn.setBackground(new java.awt.Color(0, 102, 204));
        BackBtn.setForeground(new java.awt.Color(255, 255, 255));
        BackBtn.setText("Main Menu");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 120, 40));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 280, -1));

        UserNameTxt.setBackground(new java.awt.Color(51, 51, 51));
        UserNameTxt.setForeground(new java.awt.Color(255, 255, 255));
        UserNameTxt.setBorder(null);
        UserNameTxt.setCaretColor(new java.awt.Color(255, 255, 255));
        UserNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(UserNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 280, 27));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 280, -1));

        PassTxt.setBackground(new java.awt.Color(51, 51, 51));
        PassTxt.setForeground(new java.awt.Color(255, 255, 255));
        PassTxt.setBorder(null);
        PassTxt.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(PassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 280, 27));

        LoginBtn.setBackground(new java.awt.Color(0, 102, 204));
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 120, 40));

        ChangePassBtn.setBackground(new java.awt.Color(0, 102, 204));
        ChangePassBtn.setForeground(new java.awt.Color(255, 255, 255));
        ChangePassBtn.setText("Change Password");
        ChangePassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePassBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ChangePassBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 160, 40));

        RelSettingLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RelSettingLbl.setForeground(new java.awt.Color(255, 255, 255));
        RelSettingLbl.setText("Related Setting :");
        jPanel1.add(RelSettingLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 120, 40));

        ClockLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ClockLbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ClockLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 160, 20));

        HeadingLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        HeadingLbl.setForeground(new java.awt.Color(255, 255, 255));
        HeadingLbl.setText("Admin Login Page");
        jPanel1.add(HeadingLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        LogOutBtn.setBackground(new java.awt.Color(0, 102, 204));
        LogOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogOutBtn.setText("Log Out");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LogOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 110, 42));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(530, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        logincheck();
        
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here
        PassTxt.setEchoChar((char)0);
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        // TODO add your handling code here:
        PassTxt.setEchoChar('*');
    }//GEN-LAST:event_jButton2MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:\

    }//GEN-LAST:event_jButton2ActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void ChangePassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePassBtnActionPerformed
        // TODO add your handling code here:
        new ChangePass().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ChangePassBtnActionPerformed

    private void UserNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameTxtActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        logout();
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    logout();
    }//GEN-LAST:event_formWindowClosing

    public static String getMD5(String input) 
    { 
        try { 
 
            MessageDigest md = MessageDigest.getInstance("MD5"); 

            byte[] messageDigest = md.digest(input.getBytes()); //digest()returns the message digest of the input to byte array
 
            BigInteger no = new BigInteger(1, messageDigest); //Byte array to signum representation
  
            String hashtext = no.toString(16); //message digest to hexa val
            while (hashtext.length() < 32) 
            { 
                hashtext = "0" + hashtext; 
            } 
            return hashtext; 
        }  
  
        catch (NoSuchAlgorithmException e) { 
            throw new RuntimeException(e); 
        } 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton ChangePassBtn;
    private javax.swing.JLabel ClockLbl;
    private javax.swing.JLabel HeadingLbl;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JLabel PassLbl;
    private javax.swing.JPasswordField PassTxt;
    private javax.swing.JLabel RelSettingLbl;
    private javax.swing.JTextField UserNameTxt;
    private javax.swing.JLabel UsernameLbl;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
