/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Anirudh
 */
public class AdminMainMenu extends DesignHome {
ResultSet rs;
PreparedStatement pstmt;
Statement stmt;
    /**
     * Creates new form AdminMainMenu
     */
    public AdminMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ViewUsersBtn = new javax.swing.JButton();
        TimeLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        ClockLbl1 = new javax.swing.JLabel();
        ClockLbl = new javax.swing.JLabel();
        ViewUsersBtn1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        HeadingLbl = new javax.swing.JLabel();
        LogOutBtn = new javax.swing.JButton();
        ViewUsersBtn2 = new javax.swing.JButton();
        ViewUsersBtn3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ViewUsersBtn.setBackground(new java.awt.Color(0, 102, 204));
        ViewUsersBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewUsersBtn.setText("View Users");
        ViewUsersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewUsersBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ViewUsersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 200, 45));

        TimeLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TimeLbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(TimeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 109, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("To View All Registered Users:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 202, -1));

        ClockLbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ClockLbl1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ClockLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 160, 20));

        ClockLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ClockLbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ClockLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 160, 20));

        ViewUsersBtn1.setBackground(new java.awt.Color(0, 102, 204));
        ViewUsersBtn1.setForeground(new java.awt.Color(255, 255, 255));
        ViewUsersBtn1.setText("View Activity Log");
        ViewUsersBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewUsersBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(ViewUsersBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 200, 45));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("To View All Logins and Logouts:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 202, -1));

        HeadingLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        HeadingLbl.setForeground(new java.awt.Color(255, 255, 255));
        HeadingLbl.setText("Admin Main Menu");
        jPanel1.add(HeadingLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        LogOutBtn.setBackground(new java.awt.Color(0, 102, 204));
        LogOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogOutBtn.setText("Log Out");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LogOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, -1, 42));

        ViewUsersBtn2.setBackground(new java.awt.Color(0, 102, 204));
        ViewUsersBtn2.setForeground(new java.awt.Color(255, 255, 255));
        ViewUsersBtn2.setText("Main Menu");
        ViewUsersBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewUsersBtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(ViewUsersBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 140, 45));

        ViewUsersBtn3.setBackground(new java.awt.Color(0, 102, 204));
        ViewUsersBtn3.setForeground(new java.awt.Color(255, 255, 255));
        ViewUsersBtn3.setText("View Users");
        ViewUsersBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewUsersBtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(ViewUsersBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 200, 45));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("To View All Pending Approvals:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 202, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(528, 528, 528)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ViewUsersBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewUsersBtn1ActionPerformed
        // TODO add your handling code here:
        new ActivityLog().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViewUsersBtn1ActionPerformed

    private void ViewUsersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewUsersBtnActionPerformed
        // TODO add your handling code here:
        new Users().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViewUsersBtnActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        logout();
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        logout();
    }//GEN-LAST:event_formWindowClosing

    private void ViewUsersBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewUsersBtn2ActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViewUsersBtn2ActionPerformed

    private void ViewUsersBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewUsersBtn3ActionPerformed
        // TODO add your handling code here:
        new ApproveUser().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_ViewUsersBtn3ActionPerformed

    public void logout()
    {
        try
        {
        String uid = "";
            con = new DesignHome().dbconn();
            String que = "Select userid, sno from ActivityLog order by Sno desc limit 1";
            stmt = con.createStatement();
            rs = stmt.executeQuery(que);
            int sno = 0;
            while(rs.next())
            {
                uid = rs.getString(1);
                sno = rs.getInt(2);
            }

            System.out.println("UserID = " + uid);
            
            String query = "update ActivityLog set logout = ? where sno = '" + sno + "';";
            pstmt = con.prepareStatement(query);

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            java.util.Date date = new java.util.Date();
            sdf.format(date);
            String datetime = date.toString();

            pstmt.setString(1, datetime);
            pstmt.executeUpdate();
            
            stmt.close();
            pstmt.close();
            rs.close();
            con.close();
            
            new Home().setVisible(true);
            this.dispose();
        }
    
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClockLbl;
    private javax.swing.JLabel ClockLbl1;
    private javax.swing.JLabel HeadingLbl;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JLabel TimeLbl;
    private javax.swing.JButton ViewUsersBtn;
    private javax.swing.JButton ViewUsersBtn1;
    private javax.swing.JButton ViewUsersBtn2;
    private javax.swing.JButton ViewUsersBtn3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
