/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

import com.email.durgesh.Email;
import static Classes.EditUser.getMD5;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Anirudh
 */
public class ChangePass extends javax.swing.JFrame
{
Connection con;
ResultSet rs;
Statement stmt;
PreparedStatement pstmt;
    /**
     * Creates new form EditUserAdmin
     */
    public ChangePass() {
        initComponents();
        clock();
        Username_setter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator5 = new javax.swing.JSeparator();
        PassTxt3 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        RegisterBtn = new javax.swing.JButton();
        ResultLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BackBtn1 = new javax.swing.JButton();
        ViewNewPassBtn = new javax.swing.JButton();
        ViewOldPassBtn = new javax.swing.JButton();
        ViewReNewPassBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        NameTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        OldPassTxt = new javax.swing.JPasswordField();
        jSeparator6 = new javax.swing.JSeparator();
        NewPassTxt = new javax.swing.JPasswordField();
        jSeparator7 = new javax.swing.JSeparator();
        RePassTxt = new javax.swing.JPasswordField();
        ClockLbl = new javax.swing.JLabel();
        HeadingLbl = new javax.swing.JLabel();

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        PassTxt3.setBackground(new java.awt.Color(51, 51, 51));
        PassTxt3.setForeground(new java.awt.Color(255, 255, 255));
        PassTxt3.setBorder(null);
        PassTxt3.setCaretColor(new java.awt.Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegisterBtn.setBackground(new java.awt.Color(0, 102, 204));
        RegisterBtn.setForeground(new java.awt.Color(255, 255, 255));
        RegisterBtn.setText("Update ");
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RegisterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 280, 50));

        ResultLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResultLbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ResultLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 554, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter new password :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Re-enter your password :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enter old password :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        BackBtn1.setBackground(new java.awt.Color(0, 102, 204));
        BackBtn1.setForeground(new java.awt.Color(255, 255, 255));
        BackBtn1.setText("Cancel");
        BackBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, 100, 35));

        ViewNewPassBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/show_password_32px.png"))); // NOI18N
        ViewNewPassBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ViewNewPassBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ViewNewPassBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ViewNewPassBtnMouseReleased(evt);
            }
        });
        ViewNewPassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewNewPassBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ViewNewPassBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 30, 27));

        ViewOldPassBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/show_password_32px.png"))); // NOI18N
        ViewOldPassBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ViewOldPassBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ViewOldPassBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ViewOldPassBtnMouseReleased(evt);
            }
        });
        ViewOldPassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewOldPassBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ViewOldPassBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 30, 27));

        ViewReNewPassBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/show_password_32px.png"))); // NOI18N
        ViewReNewPassBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ViewReNewPassBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ViewReNewPassBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ViewReNewPassBtnMouseReleased(evt);
            }
        });
        ViewReNewPassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewReNewPassBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ViewReNewPassBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 30, 27));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 280, -1));

        NameTxt.setBackground(new java.awt.Color(51, 51, 51));
        NameTxt.setForeground(new java.awt.Color(255, 255, 255));
        NameTxt.setBorder(null);
        NameTxt.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(NameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 280, 27));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 280, -1));

        OldPassTxt.setBackground(new java.awt.Color(51, 51, 51));
        OldPassTxt.setForeground(new java.awt.Color(255, 255, 255));
        OldPassTxt.setBorder(null);
        OldPassTxt.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(OldPassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 280, 27));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 280, -1));

        NewPassTxt.setBackground(new java.awt.Color(51, 51, 51));
        NewPassTxt.setForeground(new java.awt.Color(255, 255, 255));
        NewPassTxt.setBorder(null);
        NewPassTxt.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(NewPassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 280, 27));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 280, -1));

        RePassTxt.setBackground(new java.awt.Color(51, 51, 51));
        RePassTxt.setForeground(new java.awt.Color(255, 255, 255));
        RePassTxt.setBorder(null);
        RePassTxt.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(RePassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 280, 27));

        ClockLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ClockLbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ClockLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 160, 20));

        HeadingLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        HeadingLbl.setForeground(new java.awt.Color(255, 255, 255));
        HeadingLbl.setText("Change Password");
        jPanel1.add(HeadingLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int OTP = (int)(Math.random()*1000000);
    
    public void clock()
    {
        Thread clock = new Thread()
        {
            public void run()
            {
                try 
                {
                    for(;;)
                    {
                        SimpleDateFormat sdf = new SimpleDateFormat("dd/mm/yyyy HH:mm:ss");
                        Date date = new Date();
                        ClockLbl.setText(sdf.format(date)); 
                        sleep(1000);
                    }
                }
                catch (InterruptedException ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        
        };
        clock.start();
    }
    
    public void Username_setter()
    {
        try
        {
            con = new DesignHome().dbconn();
            String query = "Select Userid,(select username from users where id = userid) Username from ActivityLog order by sno desc limit 1";
            stmt = con.createStatement();
            rs = stmt.executeQuery(query);
            
            String uname = "";
            
            if(rs.next())
                uname = rs.getString("Username");
            
            NameTxt.setText(uname);
                        
            stmt.close();
            rs.close();
            con.close();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void updateuserpass()
    {
        try
            {
                con = new DesignHome().dbconn();
                con.setAutoCommit(false);
                System.out.println("Connection Established");
                
               
                int count = 0;
                String IsAdmin;
                
                String oldpass = new String(OldPassTxt.getPassword());
                oldpass = getMD5(oldpass);
                System.out.println("old = " + oldpass);
                String dbpass = "";
                String userdet = NameTxt.getText();
                
                if(userdet.equals("") || oldpass.equals(""))
                {
                    JOptionPane.showMessageDialog(null, "None of the fields can be empty");
                }
                
                
                else
                    {
                        
                            String query1 = "select password from users where username = '" + userdet + "'";
                            stmt = con.createStatement();
                            rs = stmt.executeQuery(query1);
                            System.out.println("stmt executed");
                            while(rs.next())
                            {
                                count++;
                                dbpass = rs.getString("Password");
                            }
                            if(count==0)
                            {
                                JOptionPane.showMessageDialog(null, "No User Found");
                            }

                            if(oldpass.equals(dbpass))
                            {
                                
                                String newpass = new String(NewPassTxt.getPassword());
                                
                                    if(newpass.length()>=8)
                                    {
                                        
                                    newpass = getMD5(newpass);
                                    System.out.println("new pass = " + newpass);
                                    
                                    if(!oldpass.equals(newpass))
                                    {
                                    String renewpass = new String(RePassTxt.getPassword());
                                    renewpass = getMD5(renewpass);



                                    if(renewpass.equals("") || newpass.equals(""))
                                    {
                                        JOptionPane.showMessageDialog(null, "None of the fields can be empty");
                                    }
                                    else
                                    {
                                        if(newpass.equals(renewpass))
                                        {
                                            String query2 = "Update users set Password = ? where UserName = '" + userdet + "'";
                                            pstmt = con.prepareStatement(query2);
                                            pstmt.setString(1, newpass);                                

                                            int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to make these changes to this user?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                                            if(response == JOptionPane.YES_OPTION)
                                            {
                                                pstmt.executeUpdate();
                                                con.commit();
                                                System.out.println("pstmt Executed");
                                                JOptionPane.showMessageDialog(null, "Updated Successfully!");
                                                this.dispose();
                                            }

                                            else if(response == JOptionPane.NO_OPTION)
                                            {
                                                JOptionPane.showMessageDialog(null, "Action Cancelled");
                                            }
                                        }
                                        else
                                        {
                                            JOptionPane.showMessageDialog(null, "Both New Passwords Don't Match");
                                        }
                                    }
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(null, "Old And New Passwords Can Not Be Same");
                                }
                                 try
                                    {
//                                        pstmt.close();
                                        stmt.close();
                                        rs.close();
                                        con.close();
                                    }
                                catch(SQLException e)
                                {
                                    JOptionPane.showMessageDialog(null, e.getMessage());
                                }
                                
                            }
                            else
                                JOptionPane.showMessageDialog(null, "Password must contain at least 8 characters");
                        }
                        else
                            JOptionPane.showMessageDialog(null, "Invalid Credentials");
                    }
            }
        catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }
    
    
    
    
    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        updateuserpass();
    }//GEN-LAST:event_RegisterBtnActionPerformed

    private void BackBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtn1ActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to cancel the process? You will be redirected to the previous window.", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if(response == JOptionPane.YES_OPTION)
        {
            this.dispose();
        }

        else if(response == JOptionPane.NO_OPTION)
        {
            this.setVisible(true);
        }

    }//GEN-LAST:event_BackBtn1ActionPerformed

    private void ViewOldPassBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewOldPassBtnMousePressed
        // TODO add your handling code here:
        OldPassTxt.setEchoChar((char)0);
    }//GEN-LAST:event_ViewOldPassBtnMousePressed

    private void ViewOldPassBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewOldPassBtnMouseReleased
        // TODO add your handling code here:
        OldPassTxt.setEchoChar('*');
    }//GEN-LAST:event_ViewOldPassBtnMouseReleased

    private void ViewOldPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewOldPassBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewOldPassBtnActionPerformed

    private void ViewReNewPassBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewReNewPassBtnMousePressed
        // TODO add your handling code here:
        RePassTxt.setEchoChar((char)0);
    }//GEN-LAST:event_ViewReNewPassBtnMousePressed

    private void ViewReNewPassBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewReNewPassBtnMouseReleased
        // TODO add your handling code here:
        RePassTxt.setEchoChar('*');
    }//GEN-LAST:event_ViewReNewPassBtnMouseReleased

    private void ViewReNewPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewReNewPassBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewReNewPassBtnActionPerformed

    private void ViewNewPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewNewPassBtnActionPerformed
        // TODO add your handling code here:\

    }//GEN-LAST:event_ViewNewPassBtnActionPerformed

    private void ViewNewPassBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewNewPassBtnMouseReleased
        // TODO add your handling code here:
        NewPassTxt.setEchoChar('*');
    }//GEN-LAST:event_ViewNewPassBtnMouseReleased

    private void ViewNewPassBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewNewPassBtnMousePressed
        // TODO add your handling code here
        NewPassTxt.setEchoChar((char)0);
    }//GEN-LAST:event_ViewNewPassBtnMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn1;
    private javax.swing.JLabel ClockLbl;
    private javax.swing.JLabel HeadingLbl;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JPasswordField NewPassTxt;
    private javax.swing.JPasswordField OldPassTxt;
    private javax.swing.JPasswordField PassTxt3;
    private javax.swing.JPasswordField RePassTxt;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JLabel ResultLbl;
    private javax.swing.JButton ViewNewPassBtn;
    private javax.swing.JButton ViewOldPassBtn;
    private javax.swing.JButton ViewReNewPassBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
