/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

import static java.lang.Thread.sleep;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
/**
 *
 * @author Anirudh
 */
public class Login extends DesignHome {
Connection con;
Statement stmt;
Statement stmt1;
ResultSet rs;
PreparedStatement pstmt;

    /**
     * Creates new form LogIn
     */
    public Login() 
    {
        initComponents();
        clock();
        setdetails();
    }

    public void clock()
    {
        Thread clock = new Thread()
        {
            public void run()
            {
                try 
                {
                    for(;;)
                    {
                        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                        java.util.Date date = new java.util.Date();
                        ClockLbl.setText(sdf.format(date)); 
                        sleep(1000);
                    }
                }
                catch (InterruptedException ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        
        };
        clock.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        PassLbl = new javax.swing.JLabel();
        UserNameTxt = new javax.swing.JTextField();
        PassTxt = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ClockLbl = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        HeadingLbl = new javax.swing.JLabel();
        UsernameLbl1 = new javax.swing.JLabel();
        PassLbl1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PassLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PassLbl.setForeground(new java.awt.Color(255, 255, 255));
        PassLbl.setText("Forgot Password?");
        PassLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassLblMouseClicked(evt);
            }
        });
        jPanel1.add(PassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, 20));

        UserNameTxt.setBackground(new java.awt.Color(51, 51, 51));
        UserNameTxt.setForeground(new java.awt.Color(255, 255, 255));
        UserNameTxt.setBorder(null);
        UserNameTxt.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(UserNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 319, 30));

        PassTxt.setBackground(new java.awt.Color(51, 51, 51));
        PassTxt.setForeground(new java.awt.Color(255, 255, 255));
        PassTxt.setBorder(null);
        PassTxt.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(PassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 319, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/show_password_32px.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 30, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 319, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 319, 10));

        ClockLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ClockLbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ClockLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 160, 20));

        LoginBtn.setBackground(new java.awt.Color(0, 102, 204));
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("Log-In");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 296, 46));

        BackBtn.setBackground(new java.awt.Color(0, 102, 204));
        BackBtn.setForeground(new java.awt.Color(255, 255, 255));
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, 96, 35));

        ExitBtn.setBackground(new java.awt.Color(0, 102, 204));
        ExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 100, 35));

        HeadingLbl.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        HeadingLbl.setForeground(new java.awt.Color(255, 255, 255));
        HeadingLbl.setText("Login");
        jPanel1.add(HeadingLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        UsernameLbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UsernameLbl1.setForeground(new java.awt.Color(255, 255, 255));
        UsernameLbl1.setText("Enter your UserName :");
        jPanel1.add(UsernameLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, 20));

        PassLbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PassLbl1.setForeground(new java.awt.Color(255, 255, 255));
        PassLbl1.setText("Enter your Password :");
        jPanel1.add(PassLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(530, 530, 530)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:\

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        // TODO add your handling code here:
        PassTxt.setEchoChar('*');
    }//GEN-LAST:event_jButton2MouseReleased

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here
        PassTxt.setEchoChar((char)0);
    }//GEN-LAST:event_jButton2MousePressed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:'
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        logincheck();
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void PassLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassLblMouseClicked
        // TODO add your handling code here:
        new ForgotPassword().setVisible(true);
    }//GEN-LAST:event_PassLblMouseClicked
    
    public void setdetails()
    {
        try
        {
            con = new DesignHome().dbconn();
            
            String query = "SELECT userid FROM ActivityLog ORDER BY sno desc limit 1";
            stmt = con.createStatement();
            rs = stmt.executeQuery(query);
            String uname = "";
            String uid = "";
            if(rs.next())
                uid = rs.getString(1);
            
            String query2 = "SELECT username FROM users WHERE    id = '" + uid + "'";
            stmt1 = con.createStatement();
            rs = stmt1.executeQuery(query2);
            if(rs.next())
                uname = rs.getString(1);
            
            UserNameTxt.setText(uname);
            PassTxt.setCaretPosition(0);
            
            stmt.close();
            stmt1.close();
            rs.close();
            con.close();            
            }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void logincheck()
    {
        
        String uname = UserNameTxt.getText();
        String password = new String(PassTxt.getPassword());
        String active = "";
        String encpass = getMD5(password);
        String dbpass = "";
        
        if(uname.equals("") || password.equals(""))
            JOptionPane.showMessageDialog(null, "None Of The Fields Can Be Empty");
    
        else
           {
               try
               {
                   con = new DesignHome().dbconn();
                   con.setAutoCommit(false);
                   String query = "SELECT password, id, activated, active FROM users WHERE username = '" + uname + "';";
                   String userid = "";
                   String activated = "";
                   stmt = con.createStatement();
                   rs = stmt.executeQuery(query);
                   if(rs.next())
                       {
                           dbpass = rs.getString("password");   
                           userid = rs.getString("id");
                           activated = rs.getString("activated");
                           active = rs.getString("active");
                       }
                   if(dbpass.equals(encpass))
                       {                     
                           if(activated.equals("True"))
                           {
                               if(active.equals("Yes"))
                               {
                                    String query2 = "INSERT INTO ActivityLog(UserID, Login) VALUES(?,?);";
                                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                                    java.util.Date date = new java.util.Date();
                                    sdf.format(date);
                                    String datetime = date.toString();
                                    System.out.println(datetime);

                                    try
                                    {
                                     pstmt = con.prepareStatement(query2);
                                     pstmt.setString(1, userid);
                                     pstmt.setString(2, datetime);
                                     pstmt.executeUpdate();
                                     con.commit();

                                     pstmt.close();
                                     stmt.close();
                                     pstmt.close();
                                     con.close();
                                    }
                                    catch(SQLException e)
                                    {
                                        JOptionPane.showMessageDialog(null, e.getMessage());
                                    }

                                    new MainMenu().setVisible(true);
                                    this.setVisible(false); 
                               }
                               else
                                   JOptionPane.showMessageDialog(null, "User has been deactivated");
                           }
                           else
                               JOptionPane.showMessageDialog(null, "It seems your user has not been activated yet. "
                                       + "Contact an Administrator to get your user approved!");
                       }
                   else
                       JOptionPane.showMessageDialog(null, "Invalid Credentials");
               }
               catch(SQLException E)
               {
                   JOptionPane.showMessageDialog(null, E.getMessage());
               }
           }
        }
    
    public static String getMD5(String input) 
    { 
        try { 
  
            // Static getInstance method is called with hashing MD5 
            MessageDigest md = MessageDigest.getInstance("MD5"); 
  
            // digest() method is called to calculate message digest 
            //  of an input digest() return array of byte 
            byte[] messageDigest = md.digest(input.getBytes()); 
  
            // Convert byte array into signum representation 
            BigInteger no = new BigInteger(1, messageDigest); 
  
            // Convert message digest into hex value 
            String hashtext = no.toString(16); 
            while (hashtext.length() < 32) { 
                hashtext = "0" + hashtext; 
            } 
            return hashtext; 
        }  
  
        // For specifying wrong message digest algorithms 
        catch (NoSuchAlgorithmException e) { 
            throw new RuntimeException(e); 
        } 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel ClockLbl;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JLabel HeadingLbl;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JLabel PassLbl;
    private javax.swing.JLabel PassLbl1;
    private javax.swing.JPasswordField PassTxt;
    public javax.swing.JTextField UserNameTxt;
    private javax.swing.JLabel UsernameLbl1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
